name: GCP Secret Credentials Example
on:
  push:
    branches:
      - main

env:
  GCP_PROJECT_ID: 'mywebsite-384520'
  GCP_SERVICE_ACCOUNT_KEY: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Configure Google Cloud SDK
        uses: google-github-actions/setup-gcloud@master
        with:
          project_id: ${{ env.GCP_PROJECT_ID }}
          service_account_key: ${{ env.GCP_SERVICE_ACCOUNT_KEY }}

      # You can now use the Google Cloud SDK commands or other GCP-related actions in your workflow.
      # For example, to list GCS buckets, you can add the following step:

      - name: List GCS Buckets
        run: gcloud storage buckets list

